### ISSUE TITLE
[QUESTION] [on_empty_queue] is an invalid option for [ehmtxv2]. Did you mean [allow_empty_screen]?

### ISSUE THREAD

**Issue by robudus** [lubeda/EspHoMaTriXv2#233] opened 2024-05-09 16:57 UTC
# Question

Hi i would like to compile the latest version to my esp32 but get the Error:
I use EspHome in HomeAssistant 2024.4.2

see logs for the error.

I use this yaml
https://github.com/lubeda/EspHoMaTriXv2/blob/latest/install/ulanzi-easy.yaml

Can you please help me. 

Thanks

ROBudus

## Additional information

- used Hardware:
  - ESP32

  - EspHoMaTriXv2 version: 2024.5.0

## Logs

```text
  [on_empty_queue] is an invalid option for [ehmtxv2]. Did you mean [allow_empty_screen]?
  on_empty_queue: 
    then: 
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,false,1);
          id(rgb8x32).icon_clock("calendar|day#0",1440,10,false);
```

**Comment by robudus** [comment] 2024-05-09 16:58
`substitutions:
  devicename: esphomatrixv2
  friendly_name: EspHoMaTriXv2
  board: esp32dev
  # Pin definition from https://github.com/aptonline/PixelIt_Ulanzi 
  battery_pin: GPIO34 
  ldr_pin: GPIO35 
  matrix_pin: GPIO32 
  left_button_pin: GPIO26 
  mid_button_pin: GPIO27 
  right_button_pin: GPIO14 
  scl_pin: GPIO22 
  sda_pin: GPIO21 

output:
  - platform: gpio
    pin:
      number: GPIO15
      ignore_strapping_warning: true
    id: buzzer_pin

switch:
  - platform: template
    name: "Auto-Adjust Brightness"
    id: switch_autobrightness
    icon: mdi:brightness-auto
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      if (id(aab_enable)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      lambda: |-
        id(aab_enable) = true;
    turn_off_action:
      lambda: |-
        id(aab_enable) = false;

globals:
  # aab = auto-adjustable brightness
  - id: aab_enable
    type: "bool"
    restore_value: true
    initial_value: "true"
  - id: aab_add
    type: int
    initial_value: '10'
  - id: aab_max
    type: int
    initial_value: '220'
  - id: aab_min
    type: int
    initial_value: '20'

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: "2024.5.0"
    refresh: 600s 
    components: [ ehmtxv2 ]   

esphome:
  comment: "EHMTXv2 from LuBeDa"
  name: $devicename 
  project:
    name: "Ulanzi.EHMTXv2"
    version: "2024.5.0"
  on_boot:
    then:
      - ds1307.read_time:

esp32:
  board: esp32dev

font:
  - file: MatrixChunky6.ttf
    id: px6_font
    size: 6
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz°
  
binary_sensor:
  - platform: status
    name: "$devicename Status"
  - platform: gpio
    pin:
      number: $left_button_pin
      inverted: true
    name: "Left button"
  - platform: gpio
    pin: 
      inverted: true
      number: $mid_button_pin
      mode: INPUT_PULLUP
    name: "Middle button"
  - platform: gpio
    pin: 
      number: $right_button_pin
      inverted: true
    name: "Right button"

logger:
  level: INFO

api:

sensor:
  - platform: sht3xd
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Relative Humidity"
    update_interval: 60s
  - platform: adc
    pin: $battery_pin
    name: "$devicename Battery"
    id: battery_voltage
    update_interval: 10s
    device_class: battery
    accuracy_decimals: 0
    attenuation: auto
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
      - multiply: 1.6
      - lambda: |-
          auto r = ((x - 3) / 0.69 * 100.00);
          if (r >= 100) return 100;
          if (r > 0) return r;
          if (r <= 0) return 1;
          return 0;
    unit_of_measurement: '%'
  - platform: adc
    id: light_sensor
    name: "$devicename Illuminance"
    pin: $ldr_pin
    update_interval: 10s
    attenuation: auto
    unit_of_measurement: lx
    device_class: illuminance
    accuracy_decimals: 0
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 - 15 ;
    on_value:
      then:
        - lambda: |-
            if ( id(aab_enable) ) {
              int n = x / 4 + id(aab_add); // new_value
              if (n > id(aab_max)) n = id(aab_max);
              if (n < id(aab_min)) n = id(aab_min);
              int c = id(rgb8x32)->get_brightness(); // current value
              c = c>0?c:1 ; 
              int d = (n - c) * 100 / c; // diff in %
              if ( abs(d) > 2 ) id(rgb8x32)->set_brightness(n);
            }
      
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

i2c:
  sda: $sda_pin
  scl: $scl_pin
  scan: true
  id: i2cbus

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    internal: true
    variant: WS2812
    pin: $matrix_pin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    gamma_correct: 2.0
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
    
time:
  - platform: homeassistant
    on_time_sync:
      then:
        ds1307.write_time:
  - platform: ds1307
    update_interval: never
    id: ehmtx_time

display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: false
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
      
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: "%H:%M"
  date_format: "%d.%m."
  show_seconds: false
  default_font_id: px6_font
  default_font_yoffset: 7
  special_font_id: px6_font
  special_font_yoffset: 7
  # until here
  icons: 
    - id: error
      lameid: 40530
    - id: home_assistant
      lameid: 47693
    - id: temperature
      lameid: 2056
    - id: lightbulb
      lameid: 1762
    - id: speaker
      lameid: 9136
    - id: print3d
      lameid: 55700
    - id: internet
      lameid: 51061
    - lameid: 20275
      id: temp
    - lameid: 29129
      id: garage
    - lameid: 24087
      id: door
    - lameid: 22148
      id: wind
    - lameid: 6427
      id: rain
    - lameid: 1232
      id: phone
    - lameid: 9272
      id: fire
    - lameid: 9754
      id: tv
    - lameid: 23726
      id: nature
    - lameid: 25808
      id: work
    - lameid: 22841
      id: bike
    - lameid: 32930
      id: power
    - lameid: 27283
      id: solar
    - lameid: 26034
      id: energy
    - lameid: 5807
      id: sun
    - lameid: 34801
      id: shopping
    - lameid: 37533
      id: thunder
    - lameid: 5313
      id: mic
    - lameid: 102
      id: birthday
    - lameid: 1782
      id: xmastree
    - id: lock
      lameid: 7775
  on_empty_queue:
    then:
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,false,1);
          id(rgb8x32).icon_clock("calendar|day#0",1440,10,false);

animation:
  - file: "1pixel.gif"
    id: animation_1p

image:
  - file: "1pixel.gif"
    id: image_1p`

**Comment by robudus** [comment] 2024-05-09 16:59
``
substitutions:
  devicename: esphomatrixv2
  friendly_name: EspHoMaTriXv2
  board: esp32dev
  # Pin definition from https://github.com/aptonline/PixelIt_Ulanzi 
  battery_pin: GPIO34 
  ldr_pin: GPIO35 
  matrix_pin: GPIO32 
  left_button_pin: GPIO26 
  mid_button_pin: GPIO27 
  right_button_pin: GPIO14 
  scl_pin: GPIO22 
  sda_pin: GPIO21 

output:
  - platform: gpio
    pin:
      number: GPIO15
      ignore_strapping_warning: true
    id: buzzer_pin

switch:
  - platform: template
    name: "Auto-Adjust Brightness"
    id: switch_autobrightness
    icon: mdi:brightness-auto
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      if (id(aab_enable)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      lambda: |-
        id(aab_enable) = true;
    turn_off_action:
      lambda: |-
        id(aab_enable) = false;

globals:
  # aab = auto-adjustable brightness
  - id: aab_enable
    type: "bool"
    restore_value: true
    initial_value: "true"
  - id: aab_add
    type: int
    initial_value: '10'
  - id: aab_max
    type: int
    initial_value: '220'
  - id: aab_min
    type: int
    initial_value: '20'

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: "2024.5.0"
    refresh: 600s 
    components: [ ehmtxv2 ]   

esphome:
  comment: "EHMTXv2 from LuBeDa"
  name: $devicename 
  project:
    name: "Ulanzi.EHMTXv2"
    version: "2024.5.0"
  on_boot:
    then:
      - ds1307.read_time:

esp32:
  board: esp32dev

font:
  - file: MatrixChunky6.ttf
    id: px6_font
    size: 6
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz°
  
binary_sensor:
  - platform: status
    name: "$devicename Status"
  - platform: gpio
    pin:
      number: $left_button_pin
      inverted: true
    name: "Left button"
  - platform: gpio
    pin: 
      inverted: true
      number: $mid_button_pin
      mode: INPUT_PULLUP
    name: "Middle button"
  - platform: gpio
    pin: 
      number: $right_button_pin
      inverted: true
    name: "Right button"

logger:
  level: INFO

api:

sensor:
  - platform: sht3xd
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Relative Humidity"
    update_interval: 60s
  - platform: adc
    pin: $battery_pin
    name: "$devicename Battery"
    id: battery_voltage
    update_interval: 10s
    device_class: battery
    accuracy_decimals: 0
    attenuation: auto
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
      - multiply: 1.6
      - lambda: |-
          auto r = ((x - 3) / 0.69 * 100.00);
          if (r >= 100) return 100;
          if (r > 0) return r;
          if (r <= 0) return 1;
          return 0;
    unit_of_measurement: '%'
  - platform: adc
    id: light_sensor
    name: "$devicename Illuminance"
    pin: $ldr_pin
    update_interval: 10s
    attenuation: auto
    unit_of_measurement: lx
    device_class: illuminance
    accuracy_decimals: 0
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 - 15 ;
    on_value:
      then:
        - lambda: |-
            if ( id(aab_enable) ) {
              int n = x / 4 + id(aab_add); // new_value
              if (n > id(aab_max)) n = id(aab_max);
              if (n < id(aab_min)) n = id(aab_min);
              int c = id(rgb8x32)->get_brightness(); // current value
              c = c>0?c:1 ; 
              int d = (n - c) * 100 / c; // diff in %
              if ( abs(d) > 2 ) id(rgb8x32)->set_brightness(n);
            }
      
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

i2c:
  sda: $sda_pin
  scl: $scl_pin
  scan: true
  id: i2cbus

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    internal: true
    variant: WS2812
    pin: $matrix_pin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    gamma_correct: 2.0
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
    
time:
  - platform: homeassistant
    on_time_sync:
      then:
        ds1307.write_time:
  - platform: ds1307
    update_interval: never
    id: ehmtx_time

display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: false
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
      
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: "%H:%M"
  date_format: "%d.%m."
  show_seconds: false
  default_font_id: px6_font
  default_font_yoffset: 7
  special_font_id: px6_font
  special_font_yoffset: 7
  # until here
  icons: 
    - id: error
      lameid: 40530
    - id: home_assistant
      lameid: 47693
    - id: temperature
      lameid: 2056
    - id: lightbulb
      lameid: 1762
    - id: speaker
      lameid: 9136
    - id: print3d
      lameid: 55700
    - id: internet
      lameid: 51061
    - lameid: 20275
      id: temp
    - lameid: 29129
      id: garage
    - lameid: 24087
      id: door
    - lameid: 22148
      id: wind
    - lameid: 6427
      id: rain
    - lameid: 1232
      id: phone
    - lameid: 9272
      id: fire
    - lameid: 9754
      id: tv
    - lameid: 23726
      id: nature
    - lameid: 25808
      id: work
    - lameid: 22841
      id: bike
    - lameid: 32930
      id: power
    - lameid: 27283
      id: solar
    - lameid: 26034
      id: energy
    - lameid: 5807
      id: sun
    - lameid: 34801
      id: shopping
    - lameid: 37533
      id: thunder
    - lameid: 5313
      id: mic
    - lameid: 102
      id: birthday
    - lameid: 1782
      id: xmastree
    - id: lock
      lameid: 7775
  on_empty_queue:
    then:
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,false,1);
          id(rgb8x32).icon_clock("calendar|day#0",1440,10,false);

animation:
  - file: "1pixel.gif"
    id: animation_1p

image:
  - file: "1pixel.gif"
    id: image_1p
``

**Comment by lubeda** [comment] 2024-05-09 17:04
Yes, it's a bug! It works with 2024.4.0.

I will investigate

**Comment by N3rdix** [comment] 2024-05-16 09:48
Just got the same error when copying the 2024.3.0 files to my local environment and validating the config. When restoring the files from the previous release the validation works as expected.

Using EspHome 2024.4.2. Do you mean the problem could be fixed by downgrading it to 2024.4.0, at least as a workaround until the real issue is solved?

**Comment by lubeda** [comment] 2024-05-16 16:49
I just found out:
There is no EspHoMaTriXv2 version tagged 2024.5.0! So, as fallback the default branch is used (see https://esphome.io/components/external_components#external-components), which is very old. Please use "latest" or an available version number as ref, e,g, latest or 2024.3.0,

So this is not a bug in EspHoMaTriX!

**Closed by lubeda** 2024-05-16 16:49 UTC
Labels: help wanted, question

**Comment by N3rdix** [comment] 2024-05-16 17:55
Where exactly do you mean should this "latest" be adjusted?

In my case I just have a source of type local in the yaml

**Comment by lubeda** [comment] 2024-05-17 13:13
You have to specify a valid branch under the **ref** tag in your yaml.

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: latest
    refresh: 60s 
    components: [ ehmtxv2 ]   
```

**Comment by N3rdix** [comment] 2024-05-19 08:44
I got that when using a git resource, but how to handle the error when using a local source with the files copied to a local folder?

```
external_components:
  - source:
      path: /copied_components

```

**Comment by andrewjswan** [comment] 2024-05-19 09:42
> files copied to a local folder

Copy files from `latest` branch...

**Comment by N3rdix** [comment] 2024-05-19 09:59
Ok my fault, shame on me 😀 now I got the point, thanks
